# List of blocks you can break with the pickaxe
Block Settings:
  1:
    # material list: https://helpch.at/docs/1.8/org/bukkit/Material.html
    material: "BEDROCK"
    tools:
      1:
        # Type of tool. Reference the above linked material list
        type: "DIAMOND_PICKAXE"
        # ticks to break the specific type of block
        # Set to 0 for instant break
        # Efficiency enchantments are applied as usual.
        duration: 300
        # tool durability cost
        durability: 1
        # true: item will be dropped
        # false: the block will not be dropped.
        drop: true
        # true: item will be added to the player's inventory. The above setting 'drop' must be set to false for this.
        # false: item will not be added irrespective of the above setting 'drop'
        add to inventory: false
        # permission required to mine this block with this tool
        permission: "msb.bedrock.dia_pick"
  2:
    material: "END_PORTAL_FRAME"
    tools:
      1:
        type: "WOODEN_AXE"
        duration: 500
        durability: 5
        drop: false
        add to inventory: false
        permission: "msb.endportal.wooden_axe"
      2:
        type: "DIAMOND_SPADE"
        duration: 150
        durability: 1
        drop: false
        add to inventory: true
        permission: "msb.endportal.dia_spade"

disable dragon egg teleport: true

debug: true